sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t rodiond26/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rodiond26/docker-react npm run test
